name: .NET Core CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  AZURE_WEBAPP_NAME: vite-dotnet-openapi
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "6.x.x"
  NODE_VERSION: "18.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Setup nodes.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
